name: Build Python Backend

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload backend source
        uses: actions/upload-artifact@v3
        with:
          name: backend-source
          path: backend/
