  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'

  - name: Install Python dependencies
    working-directory: backend
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Lint or Run Tests (optional)
    working-directory: backend
    run: echo "Run your tests here, or skip this step."

  - name: Upload backend source (optional)
    uses: actions/upload-artifact@v3
    with:
      name: backend-source
      path: backend/
